namespace ProjetoBase.Enumeradores
{
    public enum EnumAutorizacaoAcao
    {
        GERAR_CNM = 1,
        ABERTURA_MATRICULA = 2,
        DELETAR_CARTAO_AUTOGRAFO = 3,
        CONVERTER_DOI = 4,
        ALTERAR_GERACAO_PRENOTACAO_AUTOMATICA = 5,
        ADICIONAR_PARTE_MANUALMENTE_RTD_RPJ = 6,
        VER_ALERTA_PAGAMENTOS = 7,
        GERAR_TEXTO_PRENOTACOES_SUBSISTENTES = 8,
        SOMENTE_VISUALIZAR_CONTAS_A_RECEBER = 9,
        SOMENTE_VISUALIZAR_COMPENSACAO_CONTAS = 10,
        LIBERAR_EDICAO_MODELO_DOCUMENTO = 11,
        ENCERRAR_MATRICULA = 12,
        CADASTRAR_PESSOA_SEM_CPF = 13,
        CADASTRAR_PESSOA_SEM_CNPJ = 14,
        CADASTRAR_PESSOA_SEM_ENDERECO = 15,
        EMITIR_NFE = 16,
        SALVAR_REGISTRO_CIVIL = 17,
        SANGRIA_DE_CAIXA = 18,
        PUBLICAR_EDITAL_COM_DATA_ANTERIOR = 19
    }
}
